# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7efaec4274446b385c1ea4176f8ce45c5f396d9c384773c9c422e21efb0aae8851b90ba7e2e98ebc037e8ff18bf0180ebc9ab057fe94db31117744d7dc346fa

test:
  secret_key_base: cf9d0ce02d58b6c713ca007c432914553e921a044c3fde1cde5808ca82854d1a9866093af5c38a721775fe6266f2c53a412b16998bfec266076d5bbdb9b2aafc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
